name: Daily TIL Log
on:
  repository_dispatch:
    types: [notion_push]

jobs:
  log_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Append to history.md
        run: |
          export TZ="Asia/Tokyo"
          DATE=$(date +'%Y-%m-%d %H:%M:%S')
          
          # Makeから送られてきた内容（content）を取り出す
          CONTENT="${{ github.event.client_payload.content }}"
          
          # history.mdに「日付 | 内容」の形式で追記
          echo "- ${DATE} | ${CONTENT}" >> history.md
          
          git config user.name "mmgggg"
          git config user.email "roc9.ggg@gmail.com"
          git add history.md
          git commit -m "Update TIL: ${DATE}"
          git push
